version: '3.9'

services:
        django_web_server:
                build: .
                container_name: django_container
                command: python /code/testproject/manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/code
                ports:
                        - 8000:8000
                env_file:
                        - web.env 
