[tool.poetry]
name = "p_3_8"
version = "0.1.0"
description = ""
authors = ["MH.T <mohammad.hassan.t@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "3.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core=1.1.5"]
build-backend = "poetry.core.masonry.api"
